version: '2'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    # restart: always             # run as a service
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  odoo12:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    # command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - odoo-web-data:/etc/odoo
      - ./addons:/mnt/extra-addons
    # restart: always             # run as a service
volumes:
  odoo-web-data:
  odoo-db-data: 